### PR TITLE
Don't create new primary keys

### PR DESCRIPTION
**Pull request by quentins**

### CODE REVIEW

**Comment by quentins** [comment]
In order to make the table definitions in redshift and postgres match, I need to get rid of these extra primary keys (redshift does support the "sequence" type, which is what those primary keys were using).

I can't tell why the extra primary keys were added in the first place, so it seemed safe to remove them, but you might know more.

**Comment by dpatti** [comment]
I think I may have been under the impression that you were required to have a primary key in every table. That is not the case, and in these tables specifically, you would actually break things because many rows will have the same `_id` since we're unrolling a subdoc array. We already [index `_id` automatically](https://github.com/trello/mosql/blob/original_pk/lib/mosql/schema.rb#L47), so I would say that the additions here should just be removed.

**Comment by quentins** [comment]
Yeah, you're right. I'm shocked I didn't hit a PK collision on staging...

**Comment by dpatti** [comment]
Looks good, but you should squash (and remove specific mentions to Trello in the commit messages since this _is_ a public fork after all).

**Comment by quentins** [comment]
Okay, this should be good now.

**Comment by dpatti** [comment]
:+1:

**Pull request merged**
